language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.2

before_install:
  - sudo luarocks install luacov-coveralls

script:
  - bash -c "ls tests | xargs -I '{}' lua -lluacov 'tests/{}'"

after_success:
  - luacov-coveralls
