language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
    - secure: kK6coC9o9dwyAA5jk4wYGSOgB4NCnEGGAoAxbz8gk03GaO/QghrmWOZQ1+Zk+9r25mYxGeCLUzwm0c4mY2EWmxgyzXi39jMkBLI9v9zx52yLYPl2FlL1ptDZZBf4qZiK3r0dWERmSgxWGnt1BB/XRRQpnHcNu+vw0g7I5caj2TN7jx2dXqrclLh/CZ6bsGMKGyd05aPpGwgp73AE2wPtqREPddS2EOLKwF3mipaXZaAnBvK/Q+gOftOsWSdK9V2knchd1wOYhmUPvMSteLs843k2IfzCMwURDHt+EUbCdBXED/YmPbNW94VDjc/Gk6JjV9FlG076ojViSRy/arKfbvukvWEDx2p1ZhLMIofmpYEbRSoaZhMOznRuoJrw8S0b8pLZ8ucwM6xMk2wuWuV/Wlqxo9H8chrBhZJkRF4V3r2aHY5ZsmnKrkQL4hYJR52A4wuuU93JOBKtJtXxLj4IPfemfdF6Twr9zZ3dYWaBHsJTmZMcCE5XVy+W2Bj97rXVhk46/yCuf5Yo2Qeu67/eGMxHpEz4gQHVphq8/03Fjwqt0Gg58a+jXFaAnxUIIZw7BdYAU2ePgMlWoBVDCEhYUbfzO8g02JV3pntLtupKP1fYGg96jlGbsD97J+pBNbjWHjolBGewG1JoYCJNaWkRERe3xlyvqmCi7gM0Sj6cjgM=
  matrix:
    - LUA=lua5.2
branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install lunitx

script:
  - make coverage
  - make test

after_success:
  - coveralls -b .. -r .. -i ./src --dump c.report.json
  - luacov-coveralls -j c.report.json -v

deploy:
  skip_cleanup: true
  provider: script
  script: python3 .scripts/release.py
  on:
    tags: true
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
